const FACTS = window.CHRONO_FACTS || [];

const state = { round: 1, totalRounds: 10, score: 0, streak: 0, bestStreak: 0, current: null, guess: null, revealed: false, used: new Set(), distances: [], sound: true };
const $ = id => document.getElementById(id);
const els = {
  roundStat:$('roundStat'),scoreStat:$('scoreStat'),streakStat:$('streakStat'),progressFill:$('progressFill'),categoryPill:$('categoryPill'),eraPill:$('eraPill'),factText:$('factText'),hintBox:$('hintBox'),hintBtn:$('hintBtn'),lockBtn:$('lockBtn'),nextBtn:$('nextBtn'),resultPanel:$('resultPanel'),locationName:$('locationName'),pointsEarned:$('pointsEarned'),distanceText:$('distanceText'),contextText:$('contextText'),difficulty:$('difficulty'),roundCount:$('roundCount'),globeStage:$('globeStage'),statusText:$('statusText'),guessToast:$('guessToast'),endScreen:$('endScreen'),finalScore:$('finalScore'),bestGuess:$('bestGuess'),avgDistance:$('avgDistance'),bestStreak:$('bestStreak'),playAgainBtn:$('playAgainBtn'),soundBtn:$('soundBtn'),endTitle:$('endTitle'),endSubtitle:$('endSubtitle'),zoomInBtn:$('zoomInBtn'),zoomOutBtn:$('zoomOutBtn'),actionDock:$('actionDock'),scoreDock:$('scoreDock'),hudLocation:$('hudLocation'),hudContext:$('hudContext'),hudDistance:$('hudDistance'),hudScore:$('hudScore'),hudRating:$('hudRating'),howToBtn:$('howToBtn'),tutorial:$('tutorial'),tutorialClose:$('tutorialClose'),tutorialGotIt:$('tutorialGotIt')
};

const globe = Globe()(document.getElementById('globe'))
  .backgroundColor('rgba(0,0,0,0)').globeImageUrl('streaming-tiles').bumpImageUrl(null).showAtmosphere(true).atmosphereColor('#5bdcf7').atmosphereAltitude(0.18)
  .pointLat('lat').pointLng('lng').pointAltitude('altitude').pointRadius('radius').pointColor('color')
  .ringLat('lat').ringLng('lng').ringColor('color').ringMaxRadius('maxRadius').ringPropagationSpeed('speed').ringRepeatPeriod('repeat')
  .arcStartLat('startLat').arcStartLng('startLng').arcEndLat('endLat').arcEndLng('endLng').arcColor('color').arcAltitudeAutoScale(0.35).arcStroke(0.7).arcDashLength(0.55).arcDashGap(1.2).arcDashAnimateTime(1700)
  .onGlobeClick(({lat,lng})=>placeGuess(lat,lng));
const controls=globe.controls();
Object.assign(controls,{autoRotate:true,autoRotateSpeed:.45,enableDamping:true,dampingFactor:.08,minDistance:30,maxDistance:1600});
function resizeGlobe(){const r=els.globeStage.getBoundingClientRect();globe.width(r.width).height(r.height)}
window.addEventListener('resize',resizeGlobe);requestAnimationFrame(resizeGlobe);

function randomFact(){const d=els.difficulty.value;let pool=FACTS.filter(f=>d==='mixed'||f.difficulty===d);let available=pool.filter(f=>!state.used.has(FACTS.indexOf(f)));if(!available.length){state.used.clear();available=pool}const fact=available[Math.floor(Math.random()*available.length)];state.used.add(FACTS.indexOf(fact));return fact}
function startGame(){Object.assign(state,{round:1,totalRounds:Number(els.roundCount.value),score:0,streak:0,bestStreak:0,distances:[]});state.used.clear();els.endScreen.classList.remove('show');loadRound();updateStats()}
function loadRound(){state.current=randomFact();state.guess=null;state.revealed=false;const mapAidMode=els.difficulty.value==='mixed'?state.current.difficulty:els.difficulty.value;if(typeof globe.setMapAidMode==='function')globe.setMapAidMode(mapAidMode);els.categoryPill.textContent=state.current.category;els.eraPill.textContent=state.current.era;els.factText.textContent=state.current.fact;els.hintBox.textContent=state.current.hint;els.hintBox.classList.remove('show');els.hintBtn.disabled=false;els.hintBtn.textContent='Reveal hint';els.lockBtn.disabled=true;els.lockBtn.hidden=false;els.nextBtn.hidden=true;els.statusText.textContent='Choose a location';els.guessToast.classList.remove('show');els.hudDistance.textContent='—';els.hudScore.textContent='—';els.hudRating.textContent='';els.hudLocation.textContent='—';els.hudContext.textContent='';els.scoreDock.classList.remove('show');els.actionDock.classList.remove('with-score');globe.pointsData([]).ringsData([]).arcsData([]);controls.autoRotate=true;globe.pointOfView({lat:20,lng:0,altitude:1.45},900);updateStats()}
function placeGuess(lat,lng){if(state.revealed)return;state.guess={lat,lng};controls.autoRotate=false;globe.pointsData([{lat,lng,altitude:.012,radius:.45,color:'#65e9ff'}]);globe.ringsData([{lat,lng,color:()=> 'rgba(101,233,255,.65)',maxRadius:4,speed:2.2,repeat:800}]);els.lockBtn.disabled=false;els.statusText.textContent=`${formatCoord(lat,'N','S')}, ${formatCoord(lng,'E','W')}`;els.guessToast.classList.add('show');setTimeout(()=>els.guessToast.classList.remove('show'),1700);ping(420,.035,'sine')}
function revealAnswer(){if(!state.guess||state.revealed)return;state.revealed=true;const a=state.current;const km=haversine(state.guess.lat,state.guess.lng,a.lat,a.lng);const points=calculatePoints(km);state.score+=points;state.distances.push(km);if(km<=800)state.streak++;else state.streak=0;state.bestStreak=Math.max(state.bestStreak,state.streak);globe.pointsData([{...state.guess,altitude:.012,radius:.35,color:'#65e9ff'},{lat:a.lat,lng:a.lng,altitude:.018,radius:.55,color:'#ffd166'}]);globe.ringsData([{lat:a.lat,lng:a.lng,color:()=> 'rgba(255,209,102,.78)',maxRadius:7,speed:2.6,repeat:650}]);globe.arcsData([{startLat:state.guess.lat,startLng:state.guess.lng,endLat:a.lat,endLng:a.lng,color:['rgba(101,233,255,.85)','rgba(255,209,102,.95)']}]);globe.pointOfView({lat:a.lat,lng:a.lng,altitude:.08},1800);els.statusText.textContent=a.place;els.locationName.textContent=a.place;els.pointsEarned.innerHTML=`${points.toLocaleString()}<small>points</small>`;els.distanceText.textContent=km<.25?'Less than 250 meters away — perfect!':km<1?'Less than 1 km away — bullseye!':`${Math.round(km).toLocaleString()} km from the correct location`;els.contextText.textContent=a.context;els.hudLocation.textContent=a.place;els.hudContext.textContent=a.context;els.hudDistance.textContent=km<1?`${Math.round(km*1000)} m`:`${Math.round(km).toLocaleString()} km`;els.hudScore.textContent=`${points.toLocaleString()} / 10,000`;els.hudRating.textContent=points>=9000?'Bullseye!':points>=7000?'Excellent':points>=4500?'Great':points>=2000?'Close':'Keep exploring';els.scoreDock.classList.add('show');els.actionDock.classList.add('with-score');els.lockBtn.hidden=true;els.hintBtn.disabled=true;els.nextBtn.hidden=false;els.nextBtn.textContent=state.round>=state.totalRounds?'See final score →':'Next fact →';updateStats();scoreSound(points)}
function nextRound(){if(state.round>=state.totalRounds)return showEndScreen();state.round++;loadRound()}
function showEndScreen(){const best=Math.min(...state.distances),avg=state.distances.reduce((a,b)=>a+b,0)/state.distances.length,ratio=state.score/(state.totalRounds*10000);let title='Curious Traveler',subtitle='You found history across the globe.';if(ratio>=.86){title='Master Historian';subtitle='You navigate the past like you were there.'}else if(ratio>=.68){title='History Hunter';subtitle='Your geographic instincts are seriously sharp.'}else if(ratio>=.48){title='Time Traveler';subtitle='A strong trip through human history.'}els.endTitle.textContent=title;els.endSubtitle.textContent=subtitle;els.finalScore.innerHTML=`${state.score.toLocaleString()}<small>total points</small>`;els.bestGuess.textContent=`${Math.round(best).toLocaleString()} km`;els.avgDistance.textContent=`${Math.round(avg).toLocaleString()} km`;els.bestStreak.textContent=state.bestStreak;els.endScreen.classList.add('show');flourish()}
function updateStats(){els.roundStat.textContent=`${state.round} / ${state.totalRounds}`;els.scoreStat.textContent=state.score.toLocaleString();els.streakStat.textContent=state.streak;els.progressFill.style.width=`${state.round/state.totalRounds*100}%`}
function calculatePoints(km){if(km<.25)return 10000;if(km<1)return 9000;return Math.max(0,Math.round(10000*Math.exp(-km/1800)))}
function haversine(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,x=r(c-a),y=r(d-b),q=Math.sin(x/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function formatCoord(v,p,n){return `${Math.abs(v).toFixed(1)}°${v>=0?p:n}`}
let audioCtx;function ping(freq=440,duration=.06,type='sine',delay=0){if(!state.sound)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime+delay;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.12,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g).connect(audioCtx.destination);o.start(now);o.stop(now+duration+.02)}catch{}}
function scoreSound(p){if(p>=4000){ping(523,.12,'triangle');ping(659,.14,'triangle',.11);ping(784,.2,'triangle',.23)}else if(p>=2000){ping(440,.1);ping(587,.13,'sine',.12)}else{ping(260,.1);ping(220,.16,'sine',.11)}}function flourish(){[392,523,659,784].forEach((f,i)=>ping(f,.18,'triangle',i*.12))}
els.hintBtn.addEventListener('click',()=>{els.hintBox.classList.add('show');els.hintBtn.disabled=true;els.hintBtn.textContent='Hint revealed';ping(550,.05)});els.lockBtn.addEventListener('click',revealAnswer);els.nextBtn.addEventListener('click',nextRound);els.playAgainBtn.addEventListener('click',startGame);els.difficulty.addEventListener('change',startGame);els.roundCount.addEventListener('change',startGame);els.zoomInBtn.addEventListener('click',()=>{controls.autoRotate=false;globe.zoomBy(1.85)});els.zoomOutBtn.addEventListener('click',()=>{controls.autoRotate=false;globe.zoomBy(1/1.85)});els.soundBtn.addEventListener('click',()=>{state.sound=!state.sound;els.soundBtn.textContent=state.sound?'🔊':'🔇';if(state.sound)ping(500,.05)});
function openTutorial(){els.tutorial.classList.add('show')}function closeTutorial(){els.tutorial.classList.remove('show');localStorage.setItem('chronoglobeTutorialSeen','1')}
els.howToBtn.addEventListener('click',openTutorial);els.tutorialClose.addEventListener('click',closeTutorial);els.tutorialGotIt.addEventListener('click',closeTutorial);els.tutorial.addEventListener('click',e=>{if(e.target===els.tutorial)closeTutorial()});document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!els.lockBtn.disabled&&!state.revealed)revealAnswer();if((e.key===' '||e.key==='ArrowRight')&&state.revealed){e.preventDefault();nextRound()}if(e.key==='Escape')closeTutorial()});
startGame();if(!localStorage.getItem('chronoglobeTutorialSeen'))setTimeout(openTutorial,500);